### Variables
@baseUrl = http://localhost:8008
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhMWIyYzNkNC1lNWY2LTc4OTAtYWJjZC1lZjEyMzQ1Njc4OTAiLCJleHAiOjE3NzU4MjQ3NTEsImlhdCI6MTc3NTc4ODc1MSwicm9sIjoicHNpY29sb2dvIn0.mLIiu9vwH8x8cezUo9qesN9cKd9Emjknd5dcIo7QsMA

### Health check
GET {{baseUrl}}/health-check
Content-Type: application/json

### Registrar nuevo Postulante
POST {{baseUrl}}/postulantes/e17439e0-79e1-47e3-b5f9-5b54367fa290
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "documento": "12345678",
  "nombre": "Juan",
  "primer_apellido": "Perez",
  "segundo_apellido": "Quispe",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Registrar nuevo Postulante
POST {{baseUrl}}/postulantes/d4e92ac2-882a-4e46-ae56-b2361ac5327e
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "documento": "99449988",
  "nombre": "Mauricio",
  "primer_apellido": "De la Cruz",
  "segundo_apellido": "Núñez",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Registrar nuevo Postulante
POST {{baseUrl}}/postulantes/0b9fbef0-fc03-4e24-b5d0-dfb42b537324
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "documento": "04009988",
  "nombre": "Fabrizzio",
  "primer_apellido": "Fernández",
  "segundo_apellido": "De la Torre",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Obtener el postulante por documento
GET {{baseUrl}}/postulantes?documento=04009988
Content-Type: application/json
Authorization: Bearer {{token}}


### Obtener el postulante por id
GET {{baseUrl}}/postulantes?id=0b9fbef0-fc03-4e24-b5d0-dfb42b537324
Content-Type: application/json
Authorization: Bearer {{token}}

### Obtener lista de postulantes
GET {{baseUrl}}/postulantes
Content-Type: application/json
Authorization: Bearer {{token}}
