### Variables
@baseUrl = http://localhost:8008
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhMWIyYzNkNC1lNWY2LTc4OTAtYWJjZC1lZjEyMzQ1Njc4OTAiLCJleHAiOjE3NzU4MjYxMzAsImlhdCI6MTc3NTc5MDEzMCwicm9sIjoicHNpY29sb2dvIn0.kP1kNgrrdwrPf5MUsSKFuqRMB82dYoIMOR6p3h29WS4

### Revisar la evaluacion
POST {{baseUrl}}/revisiones/2c687ba9-9120-4d08-8290-233551b81c50
Content-Type: application/json

{
  "evaluacion_id": "2cf52b7a-0ee3-43a9-9b89-4a8baaa22250",
  "examenes": [
    {
        "examen_id": "19573e4f-321d-41ad-a8a9-3807c6fd3d65",
        "observacion": "Ejemplo 01."
    },
    {
      "examen_id": "2fcb7b0d-30e2-4853-afbf-9df79dd83ecb",
      "observacion": "Ejemplo 02."
    }
  ]
}

### Retorna todas las respuestas listas para ser corregidas
GET {{baseUrl}}/revisiones
Content-Type: application/json
Authorization: Bearer {{token}}

{}
