### Variables
@baseUrl = http://localhost:8008
@user = 22334455
@pass = 4455

### Agregar Evaluacion
POST {{baseUrl}}/evaluacion/{{evaluacionId}}
Content-Type: application/json

### Login del postulante
POST {{baseUrl}}/login/postulante
Content-Type: application/json

{
  "user_name": "{{user}}",
  "password": "{{pass}}"
}
