### Variables
@baseUrl = http://localhost:8008

### Login del psicologo
POST {{baseUrl}}/login/psicologo
Content-Type: application/json

{
  "documento": "44556677",
  "password": "mi_password_seguro"
}

### Login del segundo psicologo
POST {{baseUrl}}/login/psicologo
Content-Type: application/json

{
  "documento": "55667788",
  "password": "otro_password_seguro"
}
