### Variables
@baseUrl = http://localhost:8008

### Login del admin
POST {{baseUrl}}/login/admin
Content-Type: application/json

{
  "documento": "11223344",
  "password": "admin_password_seguro"
}

### Login del segundo admin
POST {{baseUrl}}/login/admin
Content-Type: application/json

{
  "documento": "22334455",
  "password": "otro_admin_password"
}
