### Variables
@baseUrl = http://localhost:8008
@examId = 19573e4f-321d-41ad-a8a9-3807c6fd3d65

### Health check
GET {{baseUrl}}/health-check
Content-Type: application/json

### Registrar nuevo Postulante
POST {{baseUrl}}/postulante/e17439e0-79e1-47e3-b5f9-5b54367fa290
Content-Type: application/json

{
  "documento": "12345678",
  "nombre": "Juan",
  "primer_apellido": "Perez",
  "segundo_apellido": "Quispe",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Registrar nuevo Postulante
POST {{baseUrl}}/postulante/d4e92ac2-882a-4e46-ae56-b2361ac5327e
Content-Type: application/json

{
  "documento": "99449988",
  "nombre": "Mauricio",
  "primer_apellido": "De la Cruz",
  "segundo_apellido": "Núñez",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Registrar nuevo Postulante
POST {{baseUrl}}/postulante/0b9fbef0-fc03-4e24-b5d0-dfb42b537324
Content-Type: application/json

{
  "documento": "04009988",
  "nombre": "Fabrizzio",
  "primer_apellido": "Fernández",
  "segundo_apellido": "De la Torre",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Obtener el postulante por documento
GET {{baseUrl}}/postulante/buscar?documento=04009988
Content-Type: application/json

### Obtener lista de postulantes
GET {{baseUrl}}/postulante
Content-Type: application/json

### Crear Examen
POST {{baseUrl}}/examen/{{examId}}
Content-Type: application/json

{
  "titulo": "Protocolo de Calificacion - Evaluacion Primaria",
  "descripcion": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eros enim",
  "puntaje_maximo": 100
}

### Agregar preguntas
POST {{baseUrl}}/examen/{{examId}}/pregunta
Content-Type: application/json

{
  "preguntas": [
    
    {
      "id": "c5f75714-88d3-49a0-a6f1-d746426fed33",
      "contenido": "¿Cuál es el símbolo químico del oxígeno?",
      "etiqueta": "no",
      "tipo_de_pregunta": "sola_respuesta",
      "imagen_ref": "",
      "alternativas": {},
      "puntaje": {
        "O": 4
      }
    }
  ]
}
