### Register a new Postulante
GET http://localhost:8000/health-check
Content-Type: application/json

### Registrar nuevo Postulante
POST http://localhost:8000/postulantes/e17439e0-79e1-47e3-b5f9-5b54367fa290
Content-Type: application/json

{
  "documento": "12345678",
  "nombre": "Juan",
  "primer_apellido": "Perez",
  "segundo_apellido": "Quispe",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Registrar nuevo Postulante
POST http://localhost:8000/postulantes/d4e92ac2-882a-4e46-ae56-b2361ac5327e
Content-Type: application/json

{
  "documento": "99449988",
  "nombre": "Mauricio",
  "primer_apellido": "De la Cruz",
  "segundo_apellido": "Núñez",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Registrar nuevo Postulante
POST http://localhost:8000/postulantes/0b9fbef0-fc03-4e24-b5d0-dfb42b537324
Content-Type: application/json

{
  "documento": "04009988",
  "nombre": "Fabrizzio",
  "primer_apellido": "Fernández",
  "segundo_apellido": "De la Torre",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Obtener el postulante por documento
GET http://localhost:8000/postulantes/buscar?documento=04009988
Content-Type: application/json

### Obtener lista de postulantes
GET http://localhost:8000/postulantes
Content-Type: application/json

### Crear Examen
POST http://localhost:8000/examen/19573e4f-321d-41ad-a8a9-3807c6fd3d65
Content-Type: application/json

{
  "titulo": "Protocolo de Calificacion - Evaluacion Primaria",
  "descripcion": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eros enim"
}

### Agregar preguntas
POST http://localhost:8000/pregunta/examen/19573e4f-321d-41ad-a8a9-3807c6fd3d65
Content-Type: application/json

{
  "preguntas": [
    {
      "Alternativas": {
        "id": "84a2c727-0ded-48e8-967c-e3cc1e35b8bc",
        "contenido": "¿Cuál es la capital de Francia?",
        "imagen_ref": "paris.jpg",
        "alternativas": {
          "A": "París",
          "B": "Londres",
          "C": "Madrid",
          "D": "Roma"
        },
        "puntos": {
          "A": 4
        }
      }
    },
    {
      "Alternativas": {
        "id": "84a2c727-0ded-48e8-967c-e3cc1e35b8bc",
        "contenido": "¿dadadsasdads?",
        "imagen_ref": "paris.jpg",
        "alternativa_correcta": "C",
        "puntaje": 4,
        "alternativas": {
          "A": "wewe",
          "B": "ewe",
          "C": "www",
          "D": "sdasd"
        }
      }
    },
    {
      "AlternativasConPuntaje": {
        "id": "84a2c727-0ded-48e8-967c-e3cc1e35b8bc",
        "contenido": "¿Cuál es la capital de Francia?",
        "etiqueta": "unico",
        "alternativas": {
          "A": "París",
          "B": "Londres",
          "C": "Madrid",
          "D": "Roma",
          "F": "Roma"
        },
        "puntos": {
          "A": 0,
          "B": 1,
          "C": 2,
          "D": 3,
          "E": 4
        }
      }
    },
    {
      "SioNoEysenck": {
        "id": "84a2c727-0ded-48e8-967c-e3cc1e35b8bc",
        "contenido": "¿Le gusta la multitud o la bulla a su alrededor?",
        "etiqueta": "extrovertido",
        "alternativas": {
          "y": "si",
          "n": "no"
        },
        "puntos": {
          "y": 0,
          "n": 1
        }
      }
    },
    {
      "Libre": {
        "id": "d1695032-4133-43f5-9275-26042db5583c",
        "contenido": "Explique el ciclo del agua.",
        "etiqueta": "extrovertido",
        "imagen_ref": null,
        "alternativas": null,
        "puntos": null
      }
    },
    {
      "SolaRespuesta": {
        "id": "c5f75714-88d3-49a0-a6f1-d746426fed33",
        "contenido": "¿Cuál es el símbolo químico del oxígeno?",
        "imagen_ref": null,
        "respuesta": {
          "o": 4
        }
      }
    },
    {
      "Alternativas": {
        "id": "b73c61e3-394e-43e6-a408-8135d57d4c38",
        "contenido": "¿Quién escribió 'Cien años de soledad'?",
        "imagen_ref": null,
        "alternativa_correcta": "C",
        "alternativas": {
          "A": "Jorge Luis Borges",
          "B": "Pablo Neruda",
          "C": "Gabriel García Márquez",
          "D": "Mario Vargas Llosa"
        }
      }
    }
  ]
}

### Agregar preguntas
POST http://localhost:8000/pregunta/examen/19573e4f-321d-41ad-a8a9-3807c6fd3d65
Content-Type: application/json

{
  "preguntas": [
    {
      "Libre": {
        "id": "8afafadf-aee1-4c68-a0ae-cf2e525ae270",
        "contenido": "Explique ede forma breve sobre el ciclo del oxigeno",
        "imagen_ref": null
      }
    }
  ]
}
