### Variables
@baseUrl = http://localhost:8008
@examId = 19573e4f-321d-41ad-a8a9-3807c6fd3d65
@examId2 = 2fcb7b0d-30e2-4853-afbf-9df79dd83ecb
@evaluacionId = 2cf52b7a-0ee3-43a9-9b89-4a8baaa22250

### Health check
GET {{baseUrl}}/health-check
Content-Type: application/json

### Registrar nuevo Postulante
POST {{baseUrl}}/postulante/e17439e0-79e1-47e3-b5f9-5b54367fa290
Content-Type: application/json

{
  "documento": "12345678",
  "nombre": "Juan",
  "primer_apellido": "Perez",
  "segundo_apellido": "Quispe",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Registrar nuevo Postulante
POST {{baseUrl}}/postulante/d4e92ac2-882a-4e46-ae56-b2361ac5327e
Content-Type: application/json

{
  "documento": "99449988",
  "nombre": "Mauricio",
  "primer_apellido": "De la Cruz",
  "segundo_apellido": "Núñez",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Registrar nuevo Postulante
POST {{baseUrl}}/postulante/0b9fbef0-fc03-4e24-b5d0-dfb42b537324
Content-Type: application/json

{
  "documento": "04009988",
  "nombre": "Fabrizzio",
  "primer_apellido": "Fernández",
  "segundo_apellido": "De la Torre",
  "fecha_nacimiento": "1990-01-01",
  "grado_instruccion": "superior",
  "genero": "masculino"
}

### Obtener el postulante por documento
GET {{baseUrl}}/postulante/buscar?documento=04009988
Content-Type: application/json

### Obtener lista de postulantes
GET {{baseUrl}}/postulante
Content-Type: application/json

### Crear Examen
POST {{baseUrl}}/examen/{{examId}}
Content-Type: application/json

{
  "titulo": "Protocolo de Calificacion - Evaluacion Primaria",
  "descripcion": "Este examen califica...",
  "instrucciones": "abcde"
}

### Agregar preguntas
PUT {{baseUrl}}/examen/{{examId}}
Content-Type: application/json

{
  "preguntas": [
    {
      "id": "84a2c727-0ded-48e8-967c-e3cc1e35b8bc",
      "contenido": "¿dadadsasdads?",
      "etiqueta": "no",
      "tipo_de_pregunta": "alternativa_unica",
      "imagen_ref": "",
      "alternativas": {
        "A": "wewe",
        "B": "ewe",
        "C": "www",
        "D": "sdasd"
      },
      "puntaje": {
        "C": 7
      }
    },
    {
      "id": "84a2c727-0ded-48e8-967c-e3cc1e35b8bc",
      "contenido": "¿Cuál es la capital de Francia?",
      "etiqueta": "no",
      "tipo_de_pregunta": "alternativa_peso",
      "imagen_ref": "",
      "alternativas": {
        "A": "Nunca",
        "B": "una o mas veces",
        "C": "de 2 a 4",
        "D": "de 3 veces a la semana",
        "E": "4 o mas veces a la semana"
      },
      "puntaje": {
        "A": 0,
        "B": 1,
        "C": 2,
        "D": 3,
        "E": 4
      }
    },
    {
      "id": "84a2c727-0ded-48e8-967c-e3cc1e35b8bc",
      "contenido": "¿Le gusta la multitud o la bulla a su alrededor?",
      "etiqueta": "extrovertido",
      "tipo_de_pregunta": "si_o_no",
      "imagen_ref": "",
      "alternativas": {
        "SI": "si",
        "NO": "no"
      },
      "puntaje": {
        "SI": 0,
        "NO": 1
      }
    },
    {
      "id": "c5f75714-88d3-49a0-a6f1-d746426fed33",
      "contenido": "¿Cuál es el símbolo químico del oxígeno?",
      "etiqueta": "no",
      "tipo_de_pregunta": "sola_respuesta",
      "imagen_ref": "",
      "alternativas": {},
      "puntaje": {
        "10": 4
      }
    }
  ]
}

### Crear Examen
POST {{baseUrl}}/examen/{{examId2}}
Content-Type: application/json

{
  "titulo": "Protocolo de Calificacion - Evaluacion Primaria",
  "descripcion": "Este examen califica...",
  "instrucciones": "Instrucciones"
}


### TEST de EYSENCK
PUT {{baseUrl}}/examen/{{examId2}}
Content-Type: application/json

{
  "preguntas": [
    {
      "id": "{{$uuid}}",
      "contenido": "¿Le gusta la multitud o la bulla a su alrededor?",
      "etiqueta": "extrovertido",
      "tipo_de_pregunta": "si_o_no",
      "imagen_ref": "",
      "alternativas": {
        "SI": "si",
        "NO": "no"
      },
      "puntaje": {
        "SI": 1,
        "NO": 0
      }
    },
    {
      "id": "{{$uuid}}",
      "contenido": "¿Tiene a menudo..??",
      "etiqueta": "extrovertido",
      "tipo_de_pregunta": "si_o_no",
      "imagen_ref": "",
      "alternativas": {
        "SI": "si",
        "NO": "no"
      },
      "puntaje": {
        "SI": 1,
        "NO": 0
      }
    },
    {
      "id": "{{$uuid}}",
      "contenido": "¿Tiene casi siempre una respuesta...?",
      "etiqueta": "extrovertido",
      "tipo_de_pregunta": "si_o_no",
      "imagen_ref": "",
      "alternativas": {
        "SI": "si",
        "NO": "no"
      },
      "puntaje": {
        "SI": 1,
        "NO": 0
      }
    },
    {
      "id": "{{$uuid}}",
      "contenido": "¿Permanece Usualmente...?",
      "etiqueta": "extrovertido",
      "tipo_de_pregunta": "si_o_no",
      "imagen_ref": "",
      "alternativas": {
        "SI": "si",
        "NO": "no"
      },
      "puntaje": {
        "SI": 0,
        "NO": 1
      }
    }
  ]
}

### Agregar Evaluacion
POST {{baseUrl}}/evaluacion/{{evaluacionId}}
Content-Type: application/json

{
  "titulo": "Proceso de evaluacion A-I",
  "descripcion": "Aqui el proceso de evaluacion para la licencia A-I"
}

### Agregar examenes a evaluacion
PUT {{baseUrl}}/evaluacion/{{evaluacionId}}
Content-Type: application/json

{
  "examenes": [
    "{{examId}}",
    "{{examId2}}"
  ]
}
