### Variables
@baseUrl = http://localhost:8008
@evaluacionId = 2cf52b7a-0ee3-43a9-9b89-4a8baaa22250

### Health check
POST {{baseUrl}}/respuesta
Content-Type: application/json

{
  "evaluacion_id": "{{evaluacionId}}",
  "postulante_id": "e17439e0-79e1-47e3-b5f9-5b54367fa290"
}

### Health check
POST {{baseUrl}}/respuesta
Content-Type: application/json

{
  "evaluacion_id": "{{evaluacionId}}",
  "postulante_id": "d4e92ac2-882a-4e46-ae56-b2361ac5327e"
}
