### Variables
@baseUrl = http://localhost:8008
@evaluacionId = 2cf52b7a-0ee3-43a9-9b89-4a8baaa22250
@postulante01 = e17439e0-79e1-47e3-b5f9-5b54367fa290
@postulante02 = d4e92ac2-882a-4e46-ae56-b2361ac5327e

### Asignar una evaluacion al postulante01
POST {{baseUrl}}/respuesta
Content-Type: application/json

{
  "evaluacion_id": "{{evaluacionId}}",
  "postulante_id": "{{postulante01}}"
}

### Asignar una evaluacion al postulante02
POST {{baseUrl}}/respuesta
Content-Type: application/json

{
  "evaluacion_id": "{{evaluacionId}}",
  "postulante_id": "{{postulante02}}"
}

### Empezar examen del postulante01
PATCH {{baseUrl}}/respuesta/2c687ba9-9120-4d08-8290-233551b81c50/empezar
Content-Type: application/json

{}

### Empezar examen del postulante02
PATCH {{baseUrl}}/respuesta/4bfa78df-3f5b-449b-aebf-dddc9dd1019f/empezar
Content-Type: application/json

{}

### Obtener repuesta del postulante01
GET {{baseUrl}}/respuesta/2c687ba9-9120-4d08-8290-233551b81c50/postulante/{{postulante01}}
Content-Type: application/json

{}

### Obtener repuesta del postulante02
GET {{baseUrl}}/respuesta/4bfa78df-3f5b-449b-aebf-dddc9dd1019f/postulante/{{postulante02}}
Content-Type: application/json

{}

### Enviar Respuesta del postulante01
PATCH {{baseUrl}}/respuesta/2c687ba9-9120-4d08-8290-233551b81c50
Content-Type: application/json

{
  "postulante_id": "{{postulante01}}",
  "evaluacion_id": "2cf52b7a-0ee3-43a9-9b89-4a8baaa22250",
  "examen_id": "19573e4f-321d-41ad-a8a9-3807c6fd3d65",
  "pregunta_id": "e06743ff-8090-49b0-98c2-bd59db7d610f",
  "respuestas": [
    "D"
  ]
}

### Finalizar la evaluacion
PATCH {{baseUrl}}/respuesta/4bfa78df-3f5b-449b-aebf-dddc9dd1019f/finalizar
Content-Type: application/json

{}

### Finalizar la evaluacion
PATCH {{baseUrl}}/respuesta/2c687ba9-9120-4d08-8290-233551b81c50/finalizar
Content-Type: application/json

{}
