FROM node:23-slim

RUN apt update && \
    apt install -y curl make && \
    rm -rf /var/lib/apt/lists/* && \
    npm install -g npm@11.3.0 && \
    npm install -g nodemon && \
    npm install -g pnpm

COPY ./scripts/start.sh /
RUN chmod +x /start.sh

USER node

WORKDIR /home/node/app
RUN pnpm config set store-dir /home/node/pnpm-store

EXPOSE 3000

CMD ["/start.sh"]
